# Generated by Django 3.2.7 on 2023-01-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, to='store.ColorVariation'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, to='store.SizeVariation'),
        ),
    ]
