# Generated by Django 3.2.7 on 2023-01-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
