# Generated by Django 3.2.7 on 2023-02-26 17:31

import buyit.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, upload_to=buyit.utils.media.store_product_gallery_upload_path),
        ),
    ]
