# Generated by Django 3.2.7 on 2023-01-06 19:43

import buyit.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=buyit.utils.media.profile_image_upload_path, verbose_name='Profile Picture'),
        ),
    ]
